#!/bin/bash

cd "$(git rev-parse --show-toplevel)" || exit
echo "Latest commit from each local branch:"
git for-each-ref --format="%(refname:short) - %(committerdate:short) - %(subject)" refs/heads/

